services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
    environment:
      - TZ=America/Chicago
      - GENERIC_TIMEZONE=America/Chicago
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://marcos-macbook-pro.mist-drum.ts.net/
      - N8N_EDITOR_BASE_URL=https://marcos-macbook-pro.mist-drum.ts.net/
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge